"""Aggregate-only audit utilities for the Arrow 002R laboratory.

No market-data payload is exported. No hypothesis is generated by this module.
"""
from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor
from dataclasses import asdict
import itertools
import json
import statistics

from ingest.paths import REPORTS
from research.cg_arrow002_lab import ROOT, FREEZE, PARENT, Spec, authorize, compare, dump, public_metrics, read, stamp


def rows():
    return {p.stem.removesuffix("_IS"):read(p) for p in sorted((ROOT/"results").glob("*_IS.json"))}


def board():
    records = rows()
    parent = records["PARENT"]["metrics"]
    print("ID                   total     $/day red    red_loss worst_month          DD   worst_day    avg_exp   peak_exp   P/avg  conc    n dual")
    for id,r in records.items():
        m = r["metrics"]
        dual = compare(m,parent)["strict_dual"]
        conc = m["best_month_concentration"] or 0
        print(f"{id:20} {m['total_pnl']:9.2f} {m['per_day']:9.2f} {m['red_months']:3} "
              f"{m['red_loss_sum']:11.2f} {m['worst_month']:11.2f} {m['max_dd']:11.2f} "
              f"{m['worst_day']:11.2f} {m['avg_exposure']:10.2f} {m['peak_exposure']:10.2f} "
              f"{m['profit_per_avg_exposure']:7.3f} {conc:5.3f} {m['trades']:4} {dual}")
    return records


def matched(ids):
    authorize("IS")
    records = rows()
    avg = records["PARENT"]["metrics"]["avg_exposure"]
    specs = []
    for id in ids:
        ticket = 4000*records[id]["metrics"]["avg_exposure"]/avg
        specs.append(Spec("MATCH_"+id,ticket=ticket,
                          mechanism=f"Parent with IS-calibrated constant ticket matching {id} average marked exposure before integer rounding"))
    dump(REPORTS/"cg_arrow002_matched_specs.json",[asdict(s) for s in specs])
    print(json.dumps([asdict(s) for s in specs],indent=2))


def archive_result(id,reason):
    authorize("IS")
    r = read(ROOT/"results"/(id+"_IS.json"))
    path = REPORTS/"cg_arrow002_superseded_is.json"
    old = read(path) if path.exists() else []
    old.append({"id":id,"archived_at":stamp(),"reason":reason,"original_timestamp":r["timestamp"],
                "spec":r["spec"],"superseded_metrics":public_metrics(r["metrics"])})
    dump(path,old)


def export():
    records = rows()
    parent = records["PARENT"]["metrics"]
    out = {id:{"spec":r["spec"],"metrics":public_metrics(r["metrics"]),
               "comparison_to_parent":compare(r["metrics"],parent),"timestamp":r["timestamp"],
               "first_timestamp":r.get("first_timestamp",r["timestamp"]),
               "engine_state_sha256":r.get("engine_state_sha256"),
               "replay_count":r.get("replay_count",1),
               "score_seconds":r["score_seconds"]} for id,r in records.items()}
    dump(REPORTS/"cg_arrow002_is_results.json",out)
    if (ROOT/"oos_complete.json").exists():
        manifest = read(FREEZE)
        ids = [r["id"] for r in manifest["finalists"]]+[r["id"] for r in manifest["controls"]]
        splits = {}
        for cohort in ("OOS","ALL"):
            vals = {id:read(ROOT/"results"/(id+"_"+cohort+".json")) for id in ids}
            p = vals["PARENT"]["metrics"]
            splits[cohort] = {id:{"metrics":public_metrics(r["metrics"]),
                                 "comparison":compare(r["metrics"],p),"timestamp":r["timestamp"],
                                 "freeze_sha256":r["freeze_sha256"]} for id,r in vals.items()}
        dump(REPORTS/"cg_arrow002_confirmation_results.json",splits)
    print(f"{stamp()} aggregate audit export complete",flush=True)


def robustness():
    authorize("IS")
    records = rows()
    parent = records["PARENT"]["metrics"]
    months = list(parent["months"])
    candidates = {id:r for id,r in records.items() if r["spec"].get("origin","CONTROL") != "CONTROL"}
    def axes(m):
        return [m["total_pnl"],-m["red_months"],m["red_loss_sum"],m["worst_month"],
                m["max_dd"],m["worst_day"],-(m["best_month_concentration"] or 1e30),
                -m["peak_exposure"],m["profit_per_avg_exposure"] or 0]
    frontier = []
    out = {}
    for id,r in candidates.items():
        m = r["metrics"]
        a = axes(m)
        dominators = []
        for other,rec in candidates.items():
            if other == id or rec["metrics"]["peak_exposure"] > 102922:
                continue
            b = axes(rec["metrics"])
            if all(y >= x-1e-8 for x,y in zip(a,b)) and any(y > x+1e-8 for x,y in zip(a,b)):
                dominators.append(other)
        if not dominators and m["peak_exposure"] <= 102922:
            frontier.append(id)
        differences = {month:m["months"][month]-parent["months"][month] for month in months}
        leave_out = {month:sum(v for key,v in differences.items() if key != month) for month in months}
        out[id] = {"month_differences_vs_parent":differences,
                   "leave_one_month_out_difference":leave_out,
                   "positive_month_differences":sum(v > 0 for v in differences.values()),
                   "positive_leave_one_out":sum(v > 0 for v in leave_out.values()),
                   "dominated_by":dominators}
        print(f"{id}: positive month deltas={out[id]['positive_month_differences']}/6, "
              f"positive leave-one-out={out[id]['positive_leave_one_out']}/6, "
              f"min leave-one-out delta={min(leave_out.values()):.2f}, dominated={bool(dominators)}")
    dump(REPORTS/"cg_arrow002_is_robustness.json",{
        "timestamp":stamp(),"cohort":"IS only","warning":"Descriptive robustness, not month-deletion strategies or independent statistical validation",
        "pareto_axes":"profit, red count/loss sum, worst month, max drawdown, worst day, concentration, peak exposure, profit/average exposure",
        "frontier":frontier,"candidates":out})
    print("PARETO:",frontier)


def resample_job(job):
    id,deltas = job
    vals = sorted(sum(deltas[i] for i in draw) for draw in itertools.product(range(6),repeat=6))
    return id,{"exact_resamples":len(vals),"positive_fraction":sum(v > 0 for v in vals)/len(vals),
               "p025_delta":vals[int(.025*(len(vals)-1))],"median_delta":statistics.median(vals),
               "p975_delta":vals[int(.975*(len(vals)-1))]}


def resampling():
    authorize("IS")
    records = rows()
    parent = records["PARENT"]["metrics"]
    jobs = [(id,[r["metrics"]["months"][m]-parent["months"][m] for m in parent["months"]])
            for id,r in records.items() if r["spec"].get("origin","CONTROL") != "CONTROL"]
    with ProcessPoolExecutor(max_workers=8) as pool:
        out = dict(pool.map(resample_job,jobs))
    dump(REPORTS/"cg_arrow002_is_month_resampling.json",{
        "timestamp":stamp(),"warning":"IS-selected strategies, only six months, no multiplicity correction: descriptive fragility diagnostic, NOT a valid post-selection confidence interval or external validation",
        "method":"All 6^6 ordered draws of six paired IS signal-month profit differences with replacement; no month deleted from a traded strategy; no return thresholds fitted",
        "candidates":out})
    for id,m in out.items():
        print(f"{id}: paired resample delta p025={m['p025_delta']:.2f}, p975={m['p975_delta']:.2f}, "
              f"positive fraction={m['positive_fraction']:.3f} (descriptive IS only)")


def ledger_summary():
    records = rows()
    parent = records["PARENT"]["metrics"]
    robust = read(REPORTS/"cg_arrow002_is_robustness.json")
    selection_path = REPORTS/"cg_arrow002_selection.json"
    selection = read(selection_path) if selection_path.exists() else {}
    selected = selection.get("finalists",{})
    frontier = set(robust["frontier"])
    path = REPORTS/"cg_arrow002_ledger.txt"
    marker = "\n=== FINAL IS LEDGER AND PARETO BOARD ===\n"
    prefix = path.read_text(encoding="utf-8").split(marker)[0]
    lines = [marker.strip(),f"Generated {stamp()}; exact full metrics/specifications: cg_arrow002_is_results.json",
             "Pnl/day denominator = 124 IS SIGNAL-month sessions. DD/day walk all actual lifecycle days.",
             "Profit/average exposure and live counts include zero-exposure dates over the common 251-day calendar.",
             "Run seconds below are per-book scalar replay, excluding shared parallel cache construction.",
             "Major cache runtimes: Wednesday ranks 110s; daily ranks 451s; full-field A9 532s;",
             "first D6 lifecycle rank preparation 74s, then cached resumption. Code/QA/research interpretation",
             "wall time is reported separately. Replays and control sizing are NOT additional hypotheses.",""]
    counts = {"REJECT":0,"PROMISING":0,"FRONTIER":0,"BLOCKED":0}
    origins = {"DIRECTED":0,"ASTRA":0,"DERIVED":0}
    for id,r in records.items():
        spec = Spec(**r["spec"])
        m = r["metrics"]
        if spec.origin == "CONTROL":
            continue
        origins[spec.origin] += 1
        comparison = compare(m,parent)
        if id in selected:
            disposition = "FRONTIER" if id in frontier else "PROMISING"
            why = selected[id]
        elif id in frontier:
            disposition = "PROMISING"
            why = "Non-dominated IS trade-off; not frozen to avoid redundant sizing neighbors or weaker total economics."
        else:
            disposition = "REJECT"
            why = ("Dominated by a completed alternative; retained as evidence, not granted an OOS look."
                   if comparison["strict_dual"] else "Fails higher-return/acceptable-smoothness mission and is dominated by a completed alternative.")
        counts[disposition] += 1
        lines.extend([f"{id} | {spec.origin} | {disposition}",
                      f"Mechanism: {spec.mechanism}",
                      "Exact spec: "+json.dumps(asdict(spec),sort_keys=True),
                      f"Control: PARENT; equal-dollar match MATCH_{id}; directed/derived parentage in predeclarations above.",
                      f"IS total={m['total_pnl']:.2f}; per_session={m['per_day']:.2f}; trades={m['trades']}; "
                      f"red_months={m['red_months']}; red_loss_sum={m['red_loss_sum']:.2f}; worst_month={m['worst_month']:.2f}; "
                      f"max_DD={m['max_dd']:.2f}; worst_day={m['worst_day']:.2f}; "
                      f"avg_exposure={m['avg_exposure']:.2f}; peak_exposure={m['peak_exposure']:.2f}; "
                      f"profit/avg_exposure={m['profit_per_avg_exposure']:.6f}; "
                      f"best_month_concentration={m['best_month_concentration']:.6f}.",
                      "Signal-month PnL: "+json.dumps(m["months"],sort_keys=True),
                      f"Strict dual={comparison['strict_dual']}; {why}",
                      f"First score={r.get('first_timestamp',r['timestamp'])}; latest exact replay={r['timestamp']}; "
                      f"scalar_seconds={r['score_seconds']:.4f}; replays={r.get('replay_count',1)}.",
                      "Children: see explicit R/D6 derivations above; no pending or post-OOS child.",""])
    lines.extend(["COMPACT PARETO BOARD (no single ranking score)",
                  "id | IS profit | $/session | red loss sum | DD | worst day | average / peak exposure | strict dual"])
    for id in robust["frontier"]:
        m = records[id]["metrics"]
        lines.append(f"{id} | {m['total_pnl']:.2f} | {m['per_day']:.2f} | {m['red_loss_sum']:.2f} | "
                     f"{m['max_dd']:.2f} | {m['worst_day']:.2f} | {m['avg_exposure']:.2f} / "
                     f"{m['peak_exposure']:.2f} | {compare(m,parent)['strict_dual']}")
    lines.extend(["",f"Completed hypotheses={sum(origins.values())}; origins={origins}; dispositions={counts}; frozen={len(selected)}.",
                  f"Separately scored controls={sum(r['spec'].get('origin','CONTROL') == 'CONTROL' for r in records.values())}.",
                  "Superseded A5/D6 causal-state audit results remain in cg_arrow002_superseded_is.json; not counted twice.",
                  "No incomplete hypothesis queue; no OOS-driven tuning; no next arrow."])
    path.write_text(prefix+"\n"+"\n".join(lines)+"\n",encoding="utf-8")
    print(f"{stamp()} complete aggregate ledger generated",flush=True)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("action",choices=["board","matched","export","robustness","resampling","ledger"])
    p.add_argument("ids",nargs="*")
    a = p.parse_args()
    if a.action == "board":
        board()
    elif a.action == "matched":
        matched(a.ids)
    elif a.action == "export":
        export()
    elif a.action == "robustness":
        robustness()
    elif a.action == "resampling":
        resampling()
    else:
        ledger_summary()


if __name__ == "__main__":
    main()
